[workspace]
resolver = "2"
members = ["crates/coa-core", "crates/coa-release", "crates/coa-registry-proto", "crates/coa-control-proto", "src-tauri"]
exclude = ["services/coa-registry", "services/coa-registry-e2e", "services/coa-coordinator", "services/coa-relay"]


[workspace.package]
version = "0.6.6"
edition = "2021"
license = "AGPL-3.0-only"

[profile.release]
lto = "thin"
codegen-units = 4
