pub mod backup;
pub mod cleanbase;
pub mod client;
pub mod config;
pub mod db;
pub mod download;
pub mod driver;
pub mod error;
pub mod firewall;
pub mod friends;
pub mod fsx;
pub mod health;
pub mod install;
pub mod layout;
pub mod logging;
pub mod pkgsource;
pub mod population;
pub mod process;
pub mod manifest;
pub mod migrations;
pub mod net;
pub mod package;
pub mod ra;
pub mod registry;
pub mod release;
pub mod update;
pub mod upnp;
pub mod signing;
pub mod srp6;

pub use error::{Error, ErrorCode, Result};

pub const MANAGER_VERSION: &str = env!("CARGO_PKG_VERSION");
