//! Phase 3: importing a portable character into a **stopped, disposable** realm (the offline importer).
//!
//! This is *not* the production importer. Production imports into a running realm are done by an in-core service
//! (`docs/PORTABLE_IMPORT_SERVICE.md`); this path exists to prove the model end to end and for realms that are stopped.
//!
//! ```text
//!   preflight (read-only snapshot)  ->  journal "prepared"  ->  ONE realm transaction  ->  mappings + journal "committed"
//!                                                                  (marker inside it)         (ONE local transaction)
//! ```
//!
//! * Goes through the existing [`Db`] abstraction; no driver is added or exposed.
//! * Everything written is generated by the typed encoder; untrusted text and blobs are hex literals only.
//! * The realm transaction allocates every guid from the realm's own tables and remaps every reference; it asserts its own
//!   result before `COMMIT`.
//! * Manager mappings are recorded **only after** the realm commit. If the process dies between the two commits, the
//!   marker row written inside the realm transaction tells [`recover_imports`] what happened.

use std::collections::BTreeSet;
use std::fmt;
use std::time::Duration;

use crate::db::Db;

use super::super::error::{PortableError, Result};
use super::super::ids::{CharacterId, ContentId, ImportId, SessionId};
use super::super::model::{PortableCharacter, Ruleset};
use super::super::store::{pet_identity, ImportAllocation, ImportState, JournalEntry, JournalKind, PlannedItem, PlannedPet, Store};
use super::plan::{build_plan, parse_report, Allocation, ImportPlan, PlanContext, SessionArm, IMPORT_LOCK};
use super::script::{self, parse_output, Query};
use super::sqlenc::Val;
use super::{realm_error, ruleset_of};

#[derive(Debug, Clone)]
pub struct ImportOptions {
    /// A realm refuses new characters beyond this per account.
    pub max_characters_per_account: u32,
    /// Database users of the game servers. A session of one of them means a realm is running.
    pub game_server_users: Vec<String>,
    /// Recovery never declares an import "not committed" before it is this old (an orphaned client process may still be
    /// finishing it).
    pub recovery_grace: Duration,
    /// How long recovery waits for an import that is still running in the realm.
    pub lock_wait_seconds: u32,
    /// What the destination's client data knows (appearances, vanity items). Without it no appearance or collection is
    /// written to the realm (all of it stays canonical); see `PORTABLE_APPEARANCE.md`.
    pub knowledge: Option<std::sync::Arc<super::knowledge::RealmKnowledge>>,
    /// The realm's content profile. With it, every import, update and session is evaluated against it **before** anything is
    /// written (an incompatible one is refused, a partly compatible one reports what stays canonical); without it nothing is evaluated.
    pub capabilities: Option<std::sync::Arc<super::super::capabilities::RealmCapabilities>>,
    /// The extension adapters this Manager has.
    pub extensions: Option<std::sync::Arc<super::super::extension::ExtensionRegistry>>,
}

impl Default for ImportOptions {
    fn default() -> Self {
        Self { max_characters_per_account: 10, game_server_users: vec!["acore".to_string()], recovery_grace: Duration::from_secs(30), lock_wait_seconds: 30, knowledge: None, capabilities: None, extensions: None }
    }
}

/// Why an import was refused before anything was written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImportProblem {
    /// The character belongs to another ruleset than this realm.
    WrongRuleset { character: Ruleset, realm: Ruleset },
    /// A session of the game server's database user exists: the realm is running. Only a stopped realm can be imported into
    /// from outside (a running realm hands out guids from memory).
    RealmRunning { sessions: u64 },
    OnlineCharacters(u64),
    AccountMissing(u32),
    /// Bot and Manager accounts are not destinations.
    InternalAccount(u32),
    AccountFull { count: u64, max: u32 },
    /// The realm's world data has no start position for this race/class.
    UnknownRaceClass { race: u64, class: u64 },
    /// Item entries the realm's `item_template` does not know: it would delete such items on load.
    MissingItems(Vec<u32>),
    MissingPetCreatures(Vec<u32>),
    /// An id of a namespace this importer does not apply (mod content, another ruleset).
    UnsupportedContent(String),
    /// An update names a realm character that does not exist or is deleted.
    CharacterUnavailable(u32),
}

impl fmt::Display for ImportProblem {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let list = |v: &[u32]| v.iter().take(10).map(u32::to_string).collect::<Vec<_>>().join(", ") + if v.len() > 10 { ", ..." } else { "" };
        match self {
            ImportProblem::WrongRuleset { character, realm } => write!(f, "the character is a {character} character and this is a {realm} realm"),
            ImportProblem::RealmRunning { sessions } => write!(f, "the realm is running ({sessions} session(s) of the game server's database user); stop it first"),
            ImportProblem::OnlineCharacters(n) => write!(f, "{n} character(s) are marked online; stop the realm first"),
            ImportProblem::AccountMissing(a) => write!(f, "game account {a} does not exist on this realm"),
            ImportProblem::InternalAccount(a) => write!(f, "account {a} belongs to a bot or the Manager"),
            ImportProblem::AccountFull { count, max } => write!(f, "the account already has {count} characters (limit {max})"),
            ImportProblem::UnknownRaceClass { race, class } => write!(f, "this realm has no start position for race {race} / class {class}"),
            ImportProblem::MissingItems(v) => write!(f, "the realm does not know these item entries: {}", list(v)),
            ImportProblem::MissingPetCreatures(v) => write!(f, "the realm does not know these pet creatures: {}", list(v)),
            ImportProblem::UnsupportedContent(s) => write!(f, "{s}"),
            ImportProblem::CharacterUnavailable(g) => write!(f, "the realm has no (undeleted) character {g}"),
        }
    }
}

#[derive(Debug, Clone, Default)]
pub struct PreflightReport {
    pub problems: Vec<ImportProblem>,
    pub warnings: Vec<String>,
    /// The name is taken (or reserved) on the realm: the character will arrive under a temporary name and rename at login.
    pub will_rename: bool,
}

/// Namespace problems that can be found without looking at the realm.
fn content_problems(model: &PortableCharacter, ruleset: Ruleset) -> Vec<ImportProblem> {
    let ns = ruleset.as_str();
    let mut bad: BTreeSet<String> = BTreeSet::new();
    let mut check = |what: &str, id: &ContentId, kind: &str| {
        if id.namespace() != ns || id.kind() != kind {
            bad.insert(format!("{what} {id} cannot be imported into a {ns} realm"));
        }
    };
    check("race", &model.identity.race, "race");
    check("class", &model.identity.class, "class");
    for item in &model.items {
        check("item", &item.entry, "item");
        if let Some(g) = &item.gift {
            check("gift", &g.entry, "item");
        }
    }
    for pet in &model.pets {
        check("pet", &pet.entry, "creature");
    }
    bad.into_iter().take(10).map(ImportProblem::UnsupportedContent).collect()
}

fn count_query(name: &str, sql: String) -> Query {
    Query { name: name.to_string(), columns: vec!["n"], sql }
}

fn users_sql(users: &[String]) -> String {
    users.iter().map(|u| Val::text(u.clone()).sql()).collect::<Vec<_>>().join(", ")
}

fn id_list(ids: &BTreeSet<u32>) -> String {
    ids.iter().map(u32::to_string).collect::<Vec<_>>().join(", ")
}

/// Look at the realm (one read-only consistent snapshot) and at the character, and say whether the import can start.
pub fn preflight(db: &Db, model: &PortableCharacter, account: u32, opts: &ImportOptions) -> Result<PreflightReport> {
    let mut report = PreflightReport::default();
    let realm_ruleset = ruleset_of(db);
    if model.ruleset != realm_ruleset {
        report.problems.push(ImportProblem::WrongRuleset { character: model.ruleset, realm: realm_ruleset });
    }
    report.problems.extend(content_problems(model, realm_ruleset));
    if !report.problems.is_empty() {
        return Ok(report);
    }
    let race = model.identity.race.id();
    let class = model.identity.class.id();
    let entries: BTreeSet<u32> = model.items.iter().map(|i| i.entry.id()).chain(model.items.iter().filter_map(|i| i.gift.as_ref().map(|g| g.entry.id()))).filter_map(|e| u32::try_from(e).ok()).collect();
    let creatures: BTreeSet<u32> = model.pets.iter().filter_map(|p| u32::try_from(p.entry.id()).ok()).collect();

    let probe = super::probe(db)?;
    let mut queries = vec![
        Query { name: "account".into(), columns: vec!["n", "username"], sql: format!("SELECT COUNT(*), IFNULL(MAX(CONCAT('x', HEX(username))), '-') FROM acore_auth.account WHERE id = {account}") },
        count_query("online", "SELECT COUNT(*) FROM acore_characters.characters WHERE online <> 0".into()),
        count_query("sessions", format!("SELECT COUNT(*) FROM information_schema.processlist WHERE id <> CONNECTION_ID() AND user IN ({})", users_sql(&opts.game_server_users))),
        count_query("account_chars", format!("SELECT COUNT(*) FROM acore_characters.characters WHERE account = {account}")),
        count_query("createinfo", format!("SELECT COUNT(*) FROM acore_world.playercreateinfo WHERE race = {race} AND class = {class}")),
    ];
    let name = Val::text(model.identity.name.clone()).sql();
    let mut taken = format!("EXISTS(SELECT 1 FROM acore_characters.characters WHERE name COLLATE utf8mb4_unicode_ci = {name} COLLATE utf8mb4_unicode_ci)");
    if probe.has("reserved_name") {
        taken.push_str(&format!(" OR EXISTS(SELECT 1 FROM acore_characters.reserved_name WHERE name COLLATE utf8mb4_unicode_ci = {name} COLLATE utf8mb4_unicode_ci)"));
    }
    queries.push(count_query("name_taken", format!("SELECT IF({taken}, 1, 0)")));
    if !entries.is_empty() {
        queries.push(Query { name: "item_entries".into(), columns: vec!["entry"], sql: format!("SELECT entry FROM acore_world.item_template WHERE entry IN ({})", id_list(&entries)) });
    }
    if !creatures.is_empty() {
        queries.push(Query { name: "creature_entries".into(), columns: vec!["entry"], sql: format!("SELECT entry FROM acore_world.creature_template WHERE entry IN ({})", id_list(&creatures)) });
    }
    let output = db.query(&script::snapshot_script(&queries)).map_err(realm_error)?;
    let raw = parse_output(&output, &queries)?;
    let one = |name: &str| -> Result<u64> { raw.section(name)?.iter().next().map(|r| r.u64("n")).transpose().map(|v| v.unwrap_or(0)) };

    let sessions = one("sessions")?;
    if sessions > 0 {
        report.problems.push(ImportProblem::RealmRunning { sessions });
    }
    let online = one("online")?;
    if online > 0 {
        report.problems.push(ImportProblem::OnlineCharacters(online));
    }
    let account_row = raw.section("account")?.iter().next().ok_or_else(|| PortableError::CorruptSnapshot("no account answer".into()))?;
    if account_row.u64("n")? == 0 {
        report.problems.push(ImportProblem::AccountMissing(account));
    } else if account_row.opt_text("username")?.is_some_and(|u| super::blockers::is_internal_account(&u)) {
        report.problems.push(ImportProblem::InternalAccount(account));
    }
    let chars = one("account_chars")?;
    if chars >= opts.max_characters_per_account as u64 {
        report.problems.push(ImportProblem::AccountFull { count: chars, max: opts.max_characters_per_account });
    }
    if one("createinfo")? == 0 {
        report.problems.push(ImportProblem::UnknownRaceClass { race, class });
    }
    report.will_rename = one("name_taken")? != 0;
    if report.will_rename {
        report.warnings.push("the name is taken or reserved on this realm: the character arrives under a temporary name and must be renamed at login".into());
    }
    let known = |name: &str| -> Result<BTreeSet<u32>> {
        if !raw.has(name) {
            return Ok(BTreeSet::new());
        }
        raw.section(name)?.iter().map(|r| r.u32("entry")).collect()
    };
    let missing_items: Vec<u32> = entries.difference(&known("item_entries")?).copied().collect();
    if !missing_items.is_empty() {
        report.problems.push(ImportProblem::MissingItems(missing_items));
    }
    let missing_pets: Vec<u32> = creatures.difference(&known("creature_entries")?).copied().collect();
    if !missing_pets.is_empty() {
        report.problems.push(ImportProblem::MissingPetCreatures(missing_pets));
    }
    Ok(report)
}

#[derive(Debug)]
pub struct ImportOutcome {
    pub import_id: ImportId,
    pub local_guid: u32,
    pub final_name: String,
    pub renamed: bool,
    pub items: usize,
    pub pets: usize,
    /// Settings sources and extensions that are in the snapshot but were deliberately not written to the realm.
    pub not_applied: Vec<String>,
    pub warnings: Vec<String>,
}

pub(crate) fn planned_items(model: &PortableCharacter) -> Vec<PlannedItem> {
    model
        .items
        .iter()
        .map(|i| PlannedItem { id: i.id, entry: i.entry.clone(), identity: super::super::identity::item_identity(&i.entry, i.random_property_id) })
        .collect()
}

pub(crate) fn planned_pets(model: &PortableCharacter) -> Vec<PlannedPet> {
    model.pets.iter().map(|p| PlannedPet { id: p.id, entry: p.entry.clone(), identity: pet_identity(&p.entry, p.pet_type, p.created_by_spell) }).collect()
}

/// Run the generated script in the realm. `Ok` carries the realm's report; any SQL error means the transaction rolled back
/// or never committed (the caller still verifies through the marker, because a lost answer is indistinguishable).
pub fn run_realm_import(db: &Db, plan: &ImportPlan) -> Result<(Allocation, bool)> {
    let output = db.query(&plan.script).map_err(realm_error)?;
    parse_report(&output)
}

/// Import the character's current canonical revision into a stopped realm.
pub fn import_character(db: &Db, store: &mut Store, character_id: CharacterId, server_id: &str, account: u32, opts: &ImportOptions) -> Result<ImportOutcome> {
    import_character_in_session(db, store, character_id, server_id, account, opts, None)
}

/// The same, arming the runtime portable session `session` on the arrival (the core takes the baseline at its first load).
pub fn import_character_in_session(db: &Db, store: &mut Store, character_id: CharacterId, server_id: &str, account: u32, opts: &ImportOptions, session: Option<SessionId>) -> Result<ImportOutcome> {
    let record = store.character(character_id)?;
    let model = store.load_snapshot(character_id, record.revision)?;
    if store.server_mappings(character_id)?.iter().any(|m| m.server_id == server_id) {
        return Err(PortableError::AlreadyOnRealm { character: character_id, server_id: server_id.to_string() });
    }

    let mut operations = vec![super::super::compat::Operation::OfflineImport];
    if session.is_some() {
        operations.push(super::super::compat::Operation::RuntimeSession);
    }
    let compatibility = super::profile::gate(opts, &model, &operations)?;
    let report = preflight(db, &model, account, opts)?;
    if !report.problems.is_empty() {
        return Err(PortableError::ImportRefused(report.problems));
    }
    let probe = super::probe(db)?;

    let items = planned_items(&model);
    let pets = planned_pets(&model);
    let ticket = store.begin_import(character_id, server_id, record.revision, &items, &pets)?;

    let plan = match build_plan(&model, &PlanContext { ruleset: ruleset_of(db), account, revision: record.revision, nonce: ticket.nonce, max_characters_per_account: opts.max_characters_per_account, game_server_users: &opts.game_server_users, probe: &probe, session: session.map(|session_id| SessionArm { session_id, character_id, generation: 1 }), knowledge: opts.knowledge.as_deref() }) {
        Ok(plan) => plan,
        Err(e) => {
            store.abort_import(ticket.import_id, &format!("the import plan could not be built: {e}"))?;
            return Err(e);
        }
    };
    debug_assert_eq!(plan.marker_data, ticket.marker, "the plan and the journal must use the same marker");

    let allocation = match run_realm_import(db, &plan) {
        Ok((alloc, true)) => alloc,
        // not committed, or the answer was lost: the marker in the realm decides
        outcome => {
            let original = outcome.err();
            return match resolve_import(db, store, ticket.import_id, opts, false)? {
                Resolution::Committed(alloc) => {
                    // the realm's own report was lost: read the final name back
                    let (final_name, renamed) = read_name(db, alloc.local_guid)?;
                    let mut not_applied = plan.not_applied_settings;
                    not_applied.extend(super::profile::after_write(Some(db), store, character_id, server_id, opts, alloc.local_guid, &model, compatibility.as_ref())?);
                    Ok(ImportOutcome { import_id: ticket.import_id, local_guid: alloc.local_guid, final_name, renamed, items: plan.counts.items, pets: plan.counts.pets, not_applied, warnings: report.warnings })
                }
                Resolution::Aborted => Err(original.unwrap_or_else(|| PortableError::RealmRead("the realm did not commit the import".into()))),
                Resolution::Pending(why) => Err(PortableError::ImportNeedsAttention { import_id: ticket.import_id, detail: format!("the outcome in the realm is not known yet ({why}); run recovery") }),
            };
        }
    };

    store.finish_import(ticket.import_id, ImportAllocation { local_guid: allocation.local_guid, item_base: allocation.item_base, pet_base: allocation.pet_base })?;
    let mut not_applied = plan.not_applied_settings;
    not_applied.extend(super::profile::after_write(Some(db), store, character_id, server_id, opts, allocation.local_guid, &model, compatibility.as_ref())?);
    Ok(ImportOutcome {
        import_id: ticket.import_id,
        local_guid: allocation.local_guid,
        final_name: allocation.final_name,
        renamed: allocation.renamed,
        items: plan.counts.items,
        pets: plan.counts.pets,
        not_applied,
        warnings: report.warnings,
    })
}

/// The name and rename flag of a character the realm holds (typed guid, fixed SQL).
fn read_name(db: &Db, guid: u32) -> Result<(String, bool)> {
    let out = db.query(&format!("SELECT CONCAT('x', HEX(name)), (at_login & 1) FROM acore_characters.characters WHERE guid = {guid}")).map_err(realm_error)?;
    let line = out.lines().next().ok_or_else(|| PortableError::CorruptSnapshot("the imported character is not in the realm".into()))?;
    let (name, flag) = line.split_once('\t').ok_or_else(|| PortableError::CorruptSnapshot("unexpected name answer".into()))?;
    let bytes = hex::decode(name.trim_start_matches('x')).map_err(|_| PortableError::CorruptSnapshot("invalid name hex".into()))?;
    Ok((String::from_utf8(bytes).map_err(|_| PortableError::CorruptSnapshot("name is not UTF-8".into()))?, flag.trim() == "1"))
}

// ---- recovery -----------------------------------------------------------------------------------------------------

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Resolution {
    /// The realm committed this import; the local records are (now) complete.
    Committed(ImportAllocation),
    /// The realm has no trace of it: it never committed.
    Aborted,
    /// Cannot be decided yet (too recent, or the realm is still running it).
    Pending(String),
}

#[derive(Debug)]
pub struct RecoveryReport {
    pub import_id: ImportId,
    pub resolution: Resolution,
}

fn recovery_queries() -> Vec<Query> {
    let q = |name: &str, columns: Vec<&'static str>| Query { name: name.to_string(), columns, sql: String::new() };
    vec![q("lock", vec!["n"]), q("marker", vec!["guid"]), q("items", vec!["n", "min", "max"]), q("pets", vec!["n", "min", "max"])]
}

/// The realm side of recovery: take the import lock (so an import that is still running finishes first), then find the
/// character that carries this import's marker.
fn recovery_script(marker: &str, wait: u32) -> String {
    let source = Val::text(super::policy::IMPORT_MARKER_SOURCE).sql();
    let data = Val::text(marker.to_string()).sql();
    format!(
        "SELECT '#T:lock';\nSELECT GET_LOCK('{IMPORT_LOCK}', {wait});\n\
         SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ;\nSTART TRANSACTION WITH CONSISTENT SNAPSHOT, READ ONLY;\n\
         SET @g := (SELECT MIN(guid) FROM acore_characters.character_settings WHERE source = {source} AND data = {data});\n\
         SELECT '#T:marker';\nSELECT IFNULL(@g, 'none');\n\
         SELECT '#T:items';\nSELECT COUNT(*), IFNULL(MIN(guid), 0), IFNULL(MAX(guid), 0) FROM acore_characters.item_instance WHERE owner_guid = @g;\n\
         SELECT '#T:pets';\nSELECT COUNT(*), IFNULL(MIN(id), 0), IFNULL(MAX(id), 0) FROM acore_characters.character_pet WHERE owner = @g;\n\
         COMMIT;\nDO RELEASE_LOCK('{IMPORT_LOCK}');\n"
    )
}

/// Decide what became of one unfinished import, and bring the local records in line with the realm.
/// `with_grace`: refuse to call an import "never committed" while it is younger than the recovery grace period.
pub fn resolve_import(db: &Db, store: &mut Store, import_id: ImportId, opts: &ImportOptions, with_grace: bool) -> Result<Resolution> {
    let entry: JournalEntry = store.import_entry(import_id)?;
    if entry.kind == JournalKind::Update {
        return super::reconcile::resolve_import_update(db, store, import_id, opts, with_grace);
    }
    match entry.state {
        ImportState::Committed => return Ok(Resolution::Committed(entry.allocation.expect("a committed entry has its allocation"))),
        ImportState::Aborted => return Ok(Resolution::Aborted),
        ImportState::NeedsAttention => return Err(PortableError::ImportNeedsAttention { import_id, detail: entry.detail.unwrap_or_default() }),
        ImportState::Prepared => {}
    }
    let output = db.query(&recovery_script(&entry.marker, opts.lock_wait_seconds)).map_err(realm_error)?;
    let queries = recovery_queries();
    let raw = parse_output(&output, &queries)?;
    let lock = raw.section("lock")?.iter().next().ok_or_else(|| PortableError::CorruptSnapshot("no lock answer".into()))?.u64("n")?;
    if lock != 1 {
        return Ok(Resolution::Pending("an import is still running in the realm".into()));
    }
    let guid_text = raw.section("marker")?.iter().next().ok_or_else(|| PortableError::CorruptSnapshot("no marker answer".into()))?.plain("guid")?;
    if guid_text == "none" {
        if with_grace && age_seconds(&entry.created_at) < opts.recovery_grace.as_secs() as i64 {
            return Ok(Resolution::Pending("the import is too recent to be called lost".into()));
        }
        store.abort_import(import_id, "the realm has no trace of this import: it never committed")?;
        return Ok(Resolution::Aborted);
    }
    let local_guid: u32 = guid_text.parse().map_err(|_| PortableError::CorruptSnapshot(format!("marker answer {guid_text:?} is not a guid")))?;

    let triple = |name: &str| -> Result<(u64, u64, u64)> {
        let r = raw.section(name)?.iter().next().ok_or_else(|| PortableError::CorruptSnapshot(format!("no {name} answer")))?;
        Ok((r.u64("n")?, r.u64("min")?, r.u64("max")?))
    };
    let (n_items, min_item, max_item) = triple("items")?;
    let (n_pets, min_pet, max_pet) = triple("pets")?;
    let contiguous = |n: u64, min: u64, max: u64| n == 0 || max - min + 1 == n;
    if n_items as usize != entry.items.len() || n_pets as usize != entry.pets.len() || !contiguous(n_items, min_item, max_item) || !contiguous(n_pets, min_pet, max_pet) {
        let detail = format!("the realm has a character with this import's marker (guid {local_guid}) but {n_items} items / {n_pets} pets where the plan had {} / {}", entry.items.len(), entry.pets.len());
        store.flag_import(import_id, &detail)?;
        return Err(PortableError::ImportNeedsAttention { import_id, detail });
    }
    let alloc = ImportAllocation { local_guid, item_base: min_item as u32, pet_base: min_pet as u32 };
    store.finish_import(import_id, alloc)?;
    Ok(Resolution::Committed(alloc))
}

fn age_seconds(created_at: &str) -> i64 {
    chrono::DateTime::parse_from_rfc3339(created_at).map(|t| (chrono::Utc::now() - t.with_timezone(&chrono::Utc)).num_seconds()).unwrap_or(i64::MAX)
}

/// Resolve every unfinished import into `server_id`. Call this before starting any new import and when the Manager starts.
pub fn recover_imports(db: &Db, store: &mut Store, server_id: &str, opts: &ImportOptions) -> Result<Vec<RecoveryReport>> {
    let mut out = Vec::new();
    for entry in store.open_imports(server_id)? {
        let resolution = resolve_import(db, store, entry.import_id, opts, true)?;
        out.push(RecoveryReport { import_id: entry.import_id, resolution });
    }
    Ok(out)
}
